### ISSUE TITLE
How can I install this along with MkDocs?

### ISSUE THREAD

**Issue by happicamper** [cmacmackin/markdown-include#10]
Hello! I'm confused with the instructions in the README, I'm able to include this extension in MkDocs:
`markdown_extensions: [markdown_include.include]`
Now, I don't have an idea how to use this extension, Here what I want to achieve is to create a file name `file.md ` with a content of:
```
[URL1]: mydocs/file1.md
[URL2]: mydocs/file2.md
[URL3]: mydocs/file3.md
```
then calling these relative paths from other **markdown files** like this:
```
Here is the [link][URL1] 
Here is the [link][URL2] 
Here is the [link][URL3] 
```
Is it possible? thanks in advance!

**Comment by erilot** [comment]
In case you're still watching this @happicamper -- 

I've gotten markdown-include to work with MkDocs by including the extension like this:
```
...
markdown_extensions:
  - markdown_include.include:
      base_path: docs
...
```
where `docs` is whatever your MkDocs base directory is ("docs" by default).

Then your includes are relative to the `docs` directory: `{! ./file.md !}` would inject the contents of `/docs/file.md`.

What you describe should work since this all happens before markdown processing.

**Comment by happicamper** [comment]
I'm bad at watching my issues! Thanks @erilot I'm able to solve this a month ago and didn't close this issue, sorry! Horay! 🍕
