### ISSUE TITLE
Incompatible with mkdocs-multirepo-plugin 

### ISSUE THREAD

**Issue by ssbarnea** [cmacmackin/markdown-include#41]
It seems that all includes used in child projects fail to render when using [mkdocs-multirepo-plugin](https://github.com/jdoiro3/mkdocs-multirepo-plugin) which is by far the most popular solution for combining multiple mkdocs sites into a single one.

What I observed is that the include renders as empty in this case, probably because it fails to find the file to include.

**Comment by ZedThree** [comment]
If that plugin is changing paths so that the relative paths are wrong in your markdown files, there's probably not much we can do in this plugin. I think you would either need to fix the paths to work in the monorepo, or write a compatibility plugin that can rewrite the paths automatically for you.

I'm afraid I won't have time to investigate this myself, but if you do come up with a solution for `markdown-include`, I'd be happy to review and merge it.

**Comment by ssbarnea** [comment]
Thanks for the quick feedback. For the moment I decided to avoid any inclusions on any mkdocs based project. That seems to be the only safe way to keep  ability to build composed sites (multiple projects). Other include methods had the same issue, so the issue is not unique to this plugin.

**Comment by ssbarnea** [comment]
Closed as I am no longer using multirepo plugin.
